railways/bookticket/urls.py
# from .views import cancle,registration,search,source_dest,payment,timetable
from django.contrib.auth import views as auth_views
from django.conf.urls import url
from . import views
app_name='bookticket'
urlpatterns = [
    url('cancle/', views.cancle,name="cancle"),
    url('registration/', views.registration,name="registration"),
    url('source_dest/', views.source_dest,name="source_dest"),
    url('search/',views.search,name="search"),
    url('payment/',views.payment,name="payment"),
    url('timetable',views.timetable,name="timetable"),
    url('ticket',views.ticket,name="ticket")
]

railways/loginmodule/urls.py
# from .views import login,invalidlogin,logout,signup,home,feedback,auth_view
from django.contrib.auth import views as auth_views
from django.conf.urls import url
from . import views

app_name = 'loginmodule'

urlpatterns = [
    url('login/', views.login , name="login"),
    url('auth/', views.auth_view, name="auth_view"),
    url('logout/', views.logout_view ,name="logout"),
    url('invalidlogin/', views.invalidlogin,name="invalidlogin"),
    url('signup/',views.signup,name="signup"),
    url('feedback/',views.feedback,name="feedback"),
    url('',views.home,name="home")
]

railways/railways/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url

urlpatterns = [
    path('admin', admin.site.urls),
    url('loginmodule/', include('loginmodule.urls',namespace='loginmodule')),
    url('bookticket/', include('bookticket.urls')),
    url('', include('loginmodule.urls',namespace='loginmodule')),
]

railways/bookticket/models.py
from django.db import models

# Create your models here.

railways/bookticket/views.py
import loginmodule
from raildata.models import Reservation, Tickets, Train, UserDetails
from django.contrib.auth.base_user import AbstractBaseUser
from django.shortcuts import redirect, render
from django.http import HttpResponseRedirect
from django.contrib import auth
from django.template.context_processors import csrf
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
import random
from raildata.models import *


@login_required(login_url='loginmodule:login')
def cancle(request):
    if request.method=="POST":
        if 'cancel' in request.POST:
            ticket = request.POST.get("ticket")
            t=Tickets.objects.get(Ticketno=ticket)
            t.delete()
            return HttpResponseRedirect("/loginmodule/home/")
        else:
            ticket = request.POST.get("ticket")
            t=Tickets.objects.get(Ticketno=ticket)
            return render(request,'cancle.html',{'t':t})
    else:
        return render(request,'cancle.html')

@login_required(login_url='loginmodule:login')
def payment(request):
     if request.method=="POST":
        return HttpResponseRedirect("/bookticket/ticket/")
     else:
        return render(request,'payment.html')

#@login_required(login_url='loginmodule:login')
def registration(request):
    if request.method=="POST":
          gender=request.POST.get('gender')
          seats=request.POST.get('seats')
          age=request.POST.get('age')
          print(seats)
          x=Reservation(Age=age,noOfPassenger=seats,Gender=gender)
          x.save()

          return HttpResponseRedirect("/bookticket/payment/")
    else:
        return render(request,'registration.html')

@login_required(login_url='loginmodule:login')
def search(request):
    if request.method == "POST":
        if request.POST.get("book"):
            arrival = request.POST.get('arrival')
            departure = request.POST.get('departure')
            trainno = request.POST.get('trainno')
            print(arrival)
            request.session['trainno']=trainno
            request.session['arrival']=arrival
            request.session['departure']=departure
            return HttpResponseRedirect("/bookticket/registration/")
        else:
            source = request.POST.get("source")
            destination=request.POST.get("dest")
            print(source)
            print(destination)
            request.session['source'] = source
            request.session['destination']=destination
            trains=Train.objects.filter(Source__icontains=source,Destination__icontains=destination)
            print(trains)
            return render(request,'search.html',{'trains':trains})

@login_required(login_url='loginmodule:login')
def source_dest(request):
    if request.method=="POST":
        source = request.POST.get("source")
        destination=request.POST.get("dest")
        print(source)
        print(destination)
        request.session['source'] = source
        request.session['destination']=destination
        trains=Train.objects.filter(Source__icontains=source,Destination__icontains=destination)
        print(trains)
        # request.session['trainno']=trains.Trainno
        # request.session['arrival']=trains.arrivaltime
        # request.session['departure']=trains.departuretime

        print(trains)
        return render(request,'search.html',{'trains':trains})
        # return HttpResponseRedirect()
    else:
        return render(request,'source_dest.html')


def timetable(request):
    t=Train.objects.all()
    print(t)
    return render(request,'timetable.html',{'t':t})


def ticket(request):
    c=request.user
    print(c)
    print(c.first_name)
    print(c.last_name)

    source=request.session['source']
    destination= request.session['destination']
    trainno=request.session['trainno']
    arrival=request.session['arrival']
    departure=request.session['departure']
    print(arrival)
    t=Tickets(Source=source,Destination=destination,Trainno=trainno,arrivaltime=arrival,departuretime=departure)

    t.save()
    return render(request,'ticket.html',{'t':t})

railways/bookticket/templates/base1.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>MyLogin!</title>

    <link
      rel="stylesheet"
      href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
      integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
      crossorigin="anonymous"
    />
    <!-- JavaScript Bundle with Popper -->
    <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>
  </head>
  <body style="background-color:#f2f2f2;">
    {% load static %}
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark sticky-top" >
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'loginmodule:home' %}">GujaratRail</a>
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'loginmodule:home' %}">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'bookticket:source_dest' %}">Book Tickets</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'bookticket:timetable' %}">Timetable</a>
            </li>

            <li class="nav-item dropdown">
              <a
                class="nav-link dropdown-toggle"
                href="#"
                id="navbarDropdownMenuLink"
                data-toggle="dropdown"
                aria-haspopup="true"
                aria-expanded="false"
              >
                More
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                <a class="dropdown-item" href="{% url 'bookticket:cancle' %}">Cancel Ticket</a>
                <a class="dropdown-item" href="{% url 'loginmodule:feedback' %}">Feedback</a>
                <a class="dropdown-item" href="{% url 'loginmodule:logout' %}">Logout</a>
              </div>
            </li>
          </ul>
        </div>
          <a align="right" href="{% url 'loginmodule:login' %}">Login</a>
        </div>
    </nav>
      {% load static %}
    
    <link rel="stylesheet" type="text/css" href="{% static 'style2.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'style1.css' %}" />

    {%block content %}
    
    
     {%endblock %}

    <footer class="footer bg-dark text-light text-center text-lg-start">
      <div class="container p-4">
        <div class="row">
          <div class="col-lg-6 col-md-12 mb-4 mb-md-0">
            <h5 class="text-uppercase">About Us</h5>
            <p>
              GujaratRail aims to work in accordance with the needs
              of its train travelers. It always updates features that 
              simplify the train journeys of the passengers.
            </p>
          </div>
      
          <div class="col-lg-6 col-md-6 mb-4 mb-md-0">
            <h5 class="text-uppercase">ADDITIONAL LINKS</h5>
            <ul class="list-unstyled lik">
              <li>
                <a href="/bookticket/source_dest/" class="text-light">Search train</a>
              </li>
              <li>
                <a href="/bookticket/timetable/" class="text-light">Time table</a>
              </li>
              <li>
                <a href="/bookticket/cancle" class="text-light">Cancel</a>
              </li>
              <li>
                <a href="/loginmodule/feedback/" class="text-light">Feedback</a>
              </li>
            </ul>
          </div>
        </div>
      </div>          
    </footer>
         
  </body>
</html>

railways/bookticket/templates/cancle.html
{% extends 'base1.html' %} {% block content %}
 
<div class="deprature_div" align="center"><br><br>
{% if t %}
<form action="" method="post" align="center">
{% csrf_token %}
 <div class="col" >
      <div class="card text-center" style="width: 30rem; height: 15rem ; margin:auto">
        <div class="card-body">
           <h4   class="card-title">Ticket no:  {{ t.Ticketno }}</h4><br>
            <h5   class="card-title">Train no:  {{ t.Trainno }}</h5><br>
          <div class="card-center">
            <p class="card-text">Arrival time:  {{ t.arrivaltime}} &nbsp; &nbsp;
           Departure time:  {{ t.departuretime}}</p>
          </div><br>
          <div class="text-center">
            <p class="card-text">Source:  {{ t.Source}}  &nbsp;&nbsp;
             Destination:  {{ t.Destination}}</p>
          </div><br>
          <input type="text" class="form-control" name="ticket" value="{{ t.Ticketno }}" hidden>
            <div class="text-center"><br><br>
            <input type="submit" name = "cancel" value = "Cancel" class = "btn btn-primary"/>
          </div>
        </div>
      </div><br><br><br><br>
    </div>
    </form>
</div></div>
{%else %}
<form action="" method="post" align="center">
  {% csrf_token %}
  <br><br>
  <h2 align="center">Cancel Ticket</h2>
 <div class="deprature_div">
 <br><br>
<div class="form-group">
  <div class="alert alert-danger">
            Are you sure you want to cancel this ticket?
        </div>
        
    <label for="inputAddress">Your Ticketno:</label>
    <input type="text" class="form-control" name="ticket" placeholder="">
  </div>

    <div class="col-auto my-1">
      <button type="submit"  class="btn btn-primary" align="center">Submit</button>
    </div>
    </div>
     </div>
</form>

{%endif%}
<br><br><br><br><br><br><br>
 {% endblock %}

railways/bookticket/templates/payment.html
{% extends 'base1.html' %} {% block content %}
<div class="registration" align="center">

<div class="container py-5">
 
 <form action="" method="post">  
 {% csrf_token %}
 <h3 class="center">Make Payment</h3><br>
    <div class="row">
        <div class="col-lg-6 mx-auto">
            <div class="card ">
                <div class="card-header">
                    <div class="bg-white shadow-sm pt-4 pl-2 pr-2 pb-2">
                        <!-- Credit card form tabs -->
                        
                        <ul role="tablist" class="nav bg-light nav-pills rounded nav-fill mb-3">
                            <li class="nav-item"> <a data-toggle="pill" href="#credit-card" class="nav-link active "> <i class="fas fa-credit-card mr-2"></i> Credit Card </a> </li>
                            <li class="nav-item"> <a data-toggle="pill" href="#paypal" class="nav-link "> <i class="fab fa-paypal mr-2"></i> Paypal </a> </li>
                            <li class="nav-item"> <a data-toggle="pill" href="#net-banking" class="nav-link "> <i class="fas fa-mobile-alt mr-2"></i> Net Banking </a> </li>
                        </ul>
                    </div> <!-- End -->
                    <!-- Credit card form content -->
                    <div class="tab-content">
                        <!-- credit card info-->
                        <div id="credit-card" class="tab-pane fade show active pt-3">
                            <form role="form">
                            {% csrf_token %}
                                <div class="form-group"> <label for="username">
                                        <h6>Card Owner</h6>
                                    </label> <input type="text" name="username" placeholder="Card Owner Name" required class="form-control "> </div>
                                <div class="form-group"> <label for="cardNumber">
                                        <h6>Card number</h6>
                                    </label>
                                    <div class="input-group"> <input type="text" name="cardNumber" placeholder="Valid card number" class="form-control " required>
                                        <div class="input-group-append"> <span class="input-group-text text-muted"> <i class="fab fa-cc-visa mx-1"></i> <i class="fab fa-cc-mastercard mx-1"></i> <i class="fab fa-cc-amex mx-1"></i> </span> </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-sm-8">
                                        <div class="form-group"> <label><span class="hidden-xs">
                                                    <h6>Expiration Date</h6>
                                                </span></label>
                                            <div class="input-group"> <input type="month" placeholder="MM" name="" class="form-control" required></div>
                                        </div>
                                    </div>
                                    <div class="col-sm-4">
                                        <div class="form-group mb-4"> <label data-toggle="tooltip" title="Three digit CV code on the back of your card">
                                                <h6>CVV <i class="fa fa-question-circle d-inline"></i></h6>
                                            </label> <input type="text" required class="form-control"> </div>
                                    </div>
                                </div>
                                <div class="card-footer"> <button type="submit" class="subscribe btn btn-primary btn-block shadow-sm"> Confirm Payment </button>
                            </form>
                        </div>
                    </div> <!-- End -->
                    <!-- Paypal info -->
                    <div id="paypal" class="tab-pane fade pt-3">
                        <h6 class="pb-2">Select your paypal account type</h6>
                        <div class="form-group "> <label class="radio-inline"> <input type="radio" name="optradio" checked> Domestic </label> <label class="radio-inline"> <input type="radio" name="optradio" class="ml-5">International </label></div>
                        <p> <button type="submit" class="btn btn-primary "><i class="fab fa-paypal mr-2"></i> Log into my Paypal</button> </p>
                        <p class="text-muted"> Note: After clicking on the button, you will be directed to a secure gateway for payment. After completing the payment process, you will be redirected back to the website to view details of your order. </p>
                    </div> <!-- End -->
                    <!-- bank transfer info -->
                    <div id="net-banking" class="tab-pane fade pt-3">
                        <div class="form-group "> <label for="Select Your Bank">
                                <h6>Select your Bank</h6>
                            </label> <select class="form-control" id="ccmonth">
                                <option value="" selected disabled>--Please select your Bank--</option>
                                <option>Bank 1</option>
                                <option>Bank 2</option>
                                <option>Bank 3</option>
                                <option>Bank 4</option>
                                <option>Bank 5</option>
                                <option>Bank 6</option>
                                <option>Bank 7</option>
                                <option>Bank 8</option>
                                <option>Bank 9</option>
                                <option>Bank 10</option>
                            </select> </div>
                        <div class="form-group">
                            <p> <button type="submit" class="btn btn-primary "><i class="fas fa-mobile-alt mr-2"></i> Proceed Pyment</button> </p>
                        </div>
                        <p class="text-muted">Note: After clicking on the button, you will be directed to a secure gateway for payment. After completing the payment process, you will be redirected back to the website to view details of your order. </p>
                    </div> <!-- End -->
                    <!-- End -->
                </div>
            </div>
        <div> 
    </div>
</div>
</div>
</form>
</div></div>
<br>

{% endblock %}

railways/bookticket/templates/registration.html
{% extends 'base1.html' %} {% block content %}

{% if form.errors %}
{% endif %}
<div>
 <div class="registration" align="center">
<form action="" method="post">
  {% csrf_token %}
  <br><br><br>
   <div class="deprature_div">
  <div class="mb-3"></br>
    <label for="" class="form-label">How many seats You want?</label>
    <input type="number" min="1",max="100"class="form-control" id="seats" name="seats" required>
  </div>

    <div class="form-group">
    <label for="inputCity">Gender</label><br>
      <input type="radio" id="male" name="gender" value="m">
      <label for="male">Male</label>
      <input type="radio" id="female" name="gender" value="f">
      <label for="female">Female</label>
      <input type="radio" id="other" name="gender" value="o">
      <label for="other">Other</label>
    </div>
    <div class="form-group">
    <label for="inputAddress">Age</label>
    <input type="number" min="18" max="70" class="form-control" id="Age" placeholder="Your Age" name="age" required>
</div><div>
  <button type="submit" class="btn btn-primary">Book Ticket</button><br><br>
</div></div>
</div>
<br><br><br><br><br><br>
</form>
      {% endblock %}

railways/bookticket/templates/search.html
{% extends 'base1.html' %} 
{% block content %}

<br><br>
<div class="container-sm">
<h1 align="center">Available Trains</h1>
<form action="" method="post">
{% csrf_token %}


   <div class="container-md" style="width: 1000px; padding: 45px 500px;">
  
   <div class="row">
 
    {% for train in trains %}
    <div class="col" >
      <div class="card text-center" style="width: 30rem; height: 15rem">
        <div class="card-body " action="" method="post">
          <h5   class="card-title">Train no:  {{ train.Trainno }}</h5>
          <div class="card-center">
            <p class="card-text">Arrival time:  {{ train.arrivaltime}} &nbsp; &nbsp;
           Departure time:  {{ train.departuretime}}</p>
          </div>
          <div class="text-center">
            <p class="card-text">Source:  {{ train.Source}}  &nbsp;&nbsp;
             Destination:  {{ train.Destination}}</p>
          </div><br>
          <div class="text-center">
            <p class="card-text">Ticket Price for 1:  {{ train.price}}</p></div>
            <div class="text-center">
            <input type="text" name="arrival" value = "{{ train.arrivaltime}}" hidden>
            <input type="text" name="trainno" value = "{{ train.Trainno}}" hidden>
            <input type="text" name="departure" value = " {{ train.departuretime}}" hidden><br>
            <input type="submit" name = "book" value = "Book" class = "btn btn-primary"/>
          </div>
        </div>
      </div><br><br>
    </div>
    {% endfor %}
  </div></div>
</form>
<br><br><br><br><br><br>
{% endblock %}

railways/bookticket/templates/source_dest.html
{% extends 'base1.html' %} {% block content %}
{% if form.errors %}

{% endif %}
<div class="source-dest" align="center">
<form action="/bookticket/search/" method="post">
{% csrf_token %} 


<br><br>
<h2>
<img src="/static/images/railicon.png"  class="rounded-circle"  class="rounded" alt="Cinque Terre" width="90" height="90">
Search.Book.Go</h2>
<br><br>
<div class="container-fluid">

    <div class="deprature_div">
    
    <div class="row">
        <div class="col">
        <label for="source" class="form-lable"><b>From</b></label>
        <input list="source" class="form-control" placeholder="Source" name="source"  required>
            <datalist id="source">
                <option value="Surat"><option value="Ahmedabad"><option value="Vadodara">
                <option value="Bhuj"><option value="Bhavnagar"><option value="Rajkot">
            </datalist>
        </div>
        <div class="col">
        <label for="dest"class="form-lable"><b>To</b></label>
        <input list="dest" class="form-control" placeholder="Destination" name="dest" >
            <datalist id="dest">
                <option value="Surat"><option value="Ahmedabad"><option value="bhavnagar">
                <option value="Vadodara"><option value="Rajkot">
                <option value="Porbandar"><option value="Bhuj">
            </datalist>
        </div>
        </div><br>
        <label for="date" class="form-lable"><b>Departure Date</b></label>
        <input type="date" class="form-control" id="date" aria-describedby="" required>
        <br><br>
      <div class="text-center">
      <input type="submit" class="btn btn-primary" value="search" name = "search"></div><br><br>
</div></div>
</form></div>

<br><br><br>

    {% endblock %}
  

railways/bookticket/templates/ticket.html
{% extends 'base1.html' %} {% block content %}

<form class="row g-3" action="" method="post" align="center">
  {% csrf_token %}
  <br><br>
 <div class="deprature_div">
 <br><br>
 <h2 align="center">Your Ticket</h2>
 <br><br><br>
 
  <div class="text-center">
      <div class="card" style="width: 30rem height: 30rem">
        <div class="card-body" action="" method="">
        
        <div class="row"> &nbsp;&nbsp;&nbsp;&nbsp; 
          <p   class="card-text">Train no:  {{ t.Trainno }}</p> &nbsp;&nbsp;&nbsp;&nbsp; 
          <p class="card-text">Ticket no: {{ t.Ticketno }}</p>
          </div>
          
          <div class="row"> &nbsp;&nbsp;&nbsp;&nbsp; 
            <p class="card-text">Source:  {{ t.Source}}</p>&nbsp;&nbsp;&nbsp;&nbsp;
            <p class="card-text">Destination:  {{ t.Destination}}</p>
          </div>
         
          <div class="row"> &nbsp;&nbsp;&nbsp;&nbsp; 
            <p class="card-text">Arrival time:  {{ t.arrivaltime}}</p>  &nbsp;&nbsp;&nbsp;&nbsp;
            <p class="card-text">Departure time:  {{ t.departuretime}}</p>
          </div>
        </div>
      </div><br><br>
    </div>
    <div class"center">
      <button type="" class="btn btn-primary" align="center">Download</button>
</div>
  </div>
  
</form>

<br><br><br><br>
</br><br>
 {% endblock %}

railways/bookticket/templates/timetable.html
{% extends 'base1.html' %}
 {% block content %}
 
<table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">Train no</th>
      <th scope="col">Route</th>
      <th scope="col">Arrival Time</th>
      <th scope="col">Departure Time</th>
      <th scope="col">Book</th>
    </tr>
  </thead>
  <tbody>
  {% for train in t %}
    <tr>
      <th scope="row">{{ train.Trainno }}</th>
      <td>{{ train.Source }} to  {{ train.Destination }} </td>
      <td> {{ train.arrivaltime }}</td>
      <td>{{ train.departuretime }}</td>
      <td><a href="/bookticket/registration/" class="btn btn-primary" type="submit">BOOK</a></td>
    </tr>
      {% endfor %}
     </tbody> 
</table>
<br><br>
 {% endblock %}