railways/bookticket/urls.py
# from .views import cancle,registration,search,source_dest,payment,timetable
from django.contrib.auth import views as auth_views
from django.conf.urls import url
from . import views
app_name='bookticket'
urlpatterns = [
    url('cancle/', views.cancle,name="cancle"),
    url('registration/', views.registration,name="registration"),
    url('source_dest/', views.source_dest,name="source_dest"),
    url('search/',views.search,name="search"),
    url('payment/',views.payment,name="payment"),
    url('timetable',views.timetable,name="timetable"),
    url('ticket',views.ticket,name="ticket")
]

railways/loginmodule/urls.py
# from .views import login,invalidlogin,logout,signup,home,feedback,auth_view
from django.contrib.auth import views as auth_views
from django.conf.urls import url
from . import views

app_name = 'loginmodule'

urlpatterns = [
    url('login/', views.login , name="login"),
    url('auth/', views.auth_view, name="auth_view"),
    url('logout/', views.logout_view ,name="logout"),
    url('invalidlogin/', views.invalidlogin,name="invalidlogin"),
    url('signup/',views.signup,name="signup"),
    url('feedback/',views.feedback,name="feedback"),
    url('',views.home,name="home")
]

railways/railways/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url

urlpatterns = [
    path('admin', admin.site.urls),
    url('loginmodule/', include('loginmodule.urls',namespace='loginmodule')),
    url('bookticket/', include('bookticket.urls')),
    url('', include('loginmodule.urls',namespace='loginmodule')),
]

railways/loginmodule/models.py
from django.db import models

# Create your models here.

railways/loginmodule/views.py
from raildata.models import Feedback, Train, UserDetails
from django.contrib.auth.base_user import AbstractBaseUser
from django.shortcuts import redirect, render
from django.http import HttpResponseRedirect
from django.contrib import auth
from django.template.context_processors import csrf
from django.contrib.auth.models import User
from .decoders import unauthenticated_user
from django.core.cache import cache
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from raildata.models import *


def login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('loginmodule:home')
    return render(request, 'login.html')


def auth_view(request):
    username = request.POST.get('username', '')
    password = request.POST.get('password', '')
    user = auth.authenticate(username=username, password=password)

    if user is not None:
        auth.login(request, user)
        return HttpResponseRedirect('/loginmodule/home/')
    else:
        return render(request, 'invalidlogin.html')


def invalidlogin(request):
    return render(request, 'invalidlogin.html')


def logout_view(request):
    auth.logout(request)
    return redirect('loginmodule:login')


def signup(request):
    if request.method == "POST":

        fname = request.POST.get('fname')
        lname = request.POST.get('lname')
        email = request.POST.get('email')
        password = request.POST.get('pass1')
        conf_pass = request.POST.get('pass2')
        age = request.POST.get('bdate')
        contact = request.POST.get('contact')
        gender = request.POST.get('gender')
        try:
            user = User.objects.get(username=request.POST.get('username'))
            return render(request, 'signup.html', {'error': "User Already Exists "})
        except User.DoesNotExist:
            user = User.objects.create_user(username=request.POST.get('username'), password=request.POST.get(
                'pass1'), first_name=request.POST.get('fname'), last_name=request.POST.get('lname'), email=request.POST.get('email'))
            # print(user)
            user.save()
            x = UserDetails(fname=fname, lname=lname, email=email, password=password,
                            conf_pass=conf_pass, age=age, contact=contact, gender=gender)
            x.save()
            auth.login(request, user)
            return render(request, 'home.html')

    else:

        return render(request, 'signup.html')


def home(request):
    if request.method == "POST":

        source = request.POST.get("source")
        destination = request.POST.get("dest")
        print(source)
        print(destination)
        trains = Train.objects.filter(
            Source__icontains=source, Destination__icontains=destination)
        print(trains)
        return render(request, 'search.html', {'trains': trains})
    else:
        return render(request, 'home.html')


@login_required(login_url='loginmodule:login')
def feedback(request):
    if request.method == "POST":
        email = request.POST.get('email')
        feedback = request.POST.get('feedback')

        x = Feedback(email=email, Feedback=feedback)
        x.save()
        return render(request, 'home.html')
    else:
        return render(request, 'feedback.html')

railways/loginmodule/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>MyLogin!</title>
    <link
      rel="stylesheet"
      href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
      integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
      crossorigin="anonymous"
    />

    <!-- JavaScript Bundle with Popper -->
    <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>

    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'style1.css' %}" />
  </head>
  <body style="background-color:#f2f2f2;">

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark sticky-top" >
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'loginmodule:home' %}">GujaratRail</a>
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'loginmodule:home' %}">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'bookticket:source_dest' %}">Book Tickets</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'bookticket:timetable' %}">Timetable</a>
            </li>

            <li class="nav-item dropdown">
              <a
                class="nav-link dropdown-toggle"
                href="#"
                id="navbarDropdownMenuLink"
                data-toggle="dropdown"
                aria-haspopup="true"
                aria-expanded="false"
              >
                More
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                <a class="dropdown-item" href="{% url 'bookticket:cancle' %}">Cancel Ticket</a>
                <a class="dropdown-item" href="{% url 'loginmodule:feedback' %}">Feedback</a>
                <a class="dropdown-item" href="{% url 'loginmodule:logout' %}">Logout</a>
              </div>
            </li>
          </ul>
        </div>
         {% if user.is_authenticated %}
         <a align="right" href="{% url 'loginmodule:logout' %}">Logout</a>
         {% else %}
          <a align="right" href="{% url 'loginmodule:login' %}">Login</a>
          {% endif %}
        </div>
    </nav>

    {%block content %} {%endblock %}


    <footer class="bg-dark text-light text-center text-lg-start">
      <div class="container p-4">
        <div class="row">
          <div class="col-lg-6 col-md-12 mb-4 mb-md-0">
            <h5 class="text-uppercase">About Us</h5>
            <p>
              GujaratRail aims to work in accordance with the needs
              of its train travelers. It always updates features that
              simplify the train journeys of the passengers.
            </p>
          </div>

          <div class="col-lg-6 col-md-6 mb-4 mb-md-0">
            <h5 class="text-uppercase">ADDITIONAL LINKS</h5>
            <ul class="list-unstyled lik">
              <li>
                <a href="/bookticket/source_dest/" class="text-light">Search train</a>
              </li>
              <li>
                <a href="/bookticket/timetable/" class="text-light">Time table</a>
              </li>
              <li>
                <a href="/bookticket/cancle" class="text-light">Cancel</a>
              </li>
              <li>
                <a href="/loginmodule/feedback/" class="text-light">Feedback</a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </footer>
</body>
</html>

railways/loginmodule/templates/feedback.html
{% extends 'base.html' %} {% block content %}

<form action="" method="POST" align="center">
  {% csrf_token %}
  <br><br><br>
  <h2 align="center">Feedbacks are always appreciated</h2>
 <div class="login_div">
 <br><br>
 <div class="form-group ">
      <label for="inputEmail4">Email</label>
      <input type="email" class="form-control" id="inputEmail4" name="email" required>
    </div>

<div class="form-group">
    <label for="inputAddress">Your Feedback</label>
    <input type="textarea" class="form-control" name="feedback" placeholder="">
  </div>

<div class="col-auto my-1">
      <button type="submit" class="btn btn-primary" align="center">Submit</button>
    </div>
    </div>
</form>
<br><br><br><br><br><br><br>
{%endblock%}

railways/loginmodule/templates/home.html
{% extends 'base.html' %} {% block content %}
  <form action="/bookticket/search/" method="post">
{% csrf_token %} 


<div class="container-fluid" style="background-image: url('/static/images/img3.jpg'); background-size:100% 100% ">
<br></br>


<br><br><br><br><br><br><br><br><br>

<div class="container  bg- text-white" >
<br><br>

  <div class="row">
    <div class="col-sm">
      <input type="text" class="form-control" placeholder="Source" name="source"  required>
      
    </div>
    <div class="col-sm">
    <input type="text" class="form-control" placeholder="Destination" name="dest" required>
    </div>
    <div class="col-sm">
        <input type="date" class="form-control" id="date" aria-describedby="" required>
    </div>
    &nbsp;   &nbsp;   &nbsp;
      <div class="col-sm">
     <button type="submit" class="btn btn-primary">Search</button> </div>
  </div>
  <br><br>
</div>
<br><br><br><br><br><br><br><br><br>


</div>

  <div  align="center" >



<br><br>
  <h1>Why Choose GujaratRail for Train Booking?</h1>
  <br><br>
<div class="card-deck" style="max-width: 800px;">
  <div class="card" >
  <img src="/static/images/24-7.jpg" class="card-img-top" alt="...">
    <div class="card-body">
      <h5 class="card-title">24*7 Customer Service </h5>
      <p class="card-text">We work 24 hours a day to make sure our availability whenever our customers need us.</p>
    </div>
    
 
  </div>
     &nbsp; 
  <div class="card" >
  <img src="/static/images/1.jpg" class="card-img-top" alt="...">
    <div class="card-body">
      <h5 class="card-title">Our Train</h5>
      <p class="card-text">Get a complete list of trains that shall be arriving at the railway station of your choice at the time selected by you.  </p>
    </div>
    
  </div>

<div class="card" >
  <img src="/static/images/refunds.jpg" class="card-img-top" alt="...">
    <div class="card-body">
      <h5 class="card-title">Instant Refunds</h5>
      <p class="card-text">Get Refunds instantly on cancellation of IndianRail train tickets  </p>
    </div>
    
 
</div>
</div>
</form>

<br><br>
{%endblock%}

railways/loginmodule/templates/invalidlogin.html
{% extends 'base.html' %}
{% block content %}
<br><br><br><br><br><br><br><br>
<h2 align="center">Invalid user name or password!</h2>
<p align="center">Click <a href="/loginmodule/login/"> here </a> to login again.</p>
<br><br><br><br><br><br><br><br><br><br>

{% endblock %}

railways/loginmodule/templates/login.html
{% extends 'base.html' %} {% block content %}
{% load static %}
{% static "images" as baseUrl %}
{% if form.errors %}
<p class="error">Invalid Username or Password</p>
{% endif %}
<div class="container-fluid" style="background-image: url(''); background-size:100% 100% ">
    {% comment %} <div class="container-fluid" style="padding: 35px 80px;">
    <div class="container">

        <div class="row">
            <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12 login_section">  {% endcomment %}
           
                <div class="login" align="center">
                    <form action="/loginmodule/auth/" method="post">
                        {% csrf_token %}
                        <br><br><br>


                        <div class="login_div">
                            <div class="mb-3">
                                <label for="exampleInputEmail1" class="form-label"><h5>Username</h5></label>
                                <input type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" name="username" required>
                            </div>
                            <div class="mb-3">
                                <label for="exampleInputPassword1" class="form-label"><h5>Password</h5></label>
                                <input type="password" class="form-control" id="exampleInputPassword1" name="password" required>
                            </div>
                            <button type="submit" class="btn btn-primary">Login</button><br><br>
                            <h4>New User? <a href="{%url 'loginmodule:signup' %}"> Signup </a> </h4>
                            <br><br> <br><br> <br><br> <br><br>
                        </div>
                </div>
            </div></div></div>
        </div></div>
    {% endblock %}

railways/loginmodule/templates/signup.html
{%extends "base.html" %} {% block content %}
<form action="" method="post">
  {% csrf_token %}
  <br /><br />
  <div class="signup_div" align="center">
   
    <div class="row">
      <div class="col">
        <label for="fname">First name</label>
        <input type="text" class="form-control" placeholder="First name" name="fname">
      </div>
      <div class="col">
        <label for="fname">Last name</label>
        <input type="text" class="form-control" placeholder="Last name" name="lname">
      </div>
    </div>
  <br>
  <div class="row">
    <div class="col ">
      <label for="inputEmail4">Email</label>
      <input type="email" class="form-control" id="inputEmail4" placeholder="Email" name="email" required>
    </div>
    <div class="col ">
      <label for="inputEmail4">Username</label>
      <input type="username" class="form-control" id="username" placeholder="username" name="username" required>
    </div>
    </div><br>
    <div class="row">
    <div class="col ">
      <label for="inputPassword4">Password</label>
      <input type="password" class="form-control" id="inputPassword4" placeholder="Password" name="pass1" required>
    </div>
    <div class="col ">
      <label for="inputPassword4">Confirm Password</label>
      <input type="password" class="form-control" id="inputPassword4" placeholder="Confirm Password" name="pass2" required>
    </div>
</div>
<br>
<div class="row">
  <div class="col">
    <label for="inputAddress">Birthdate</label>
    <input type="date" class="form-control" id="Age" placeholder="Your BirthDate" name="bdate" required>
  </div>
    <div class="col">
      <label for="Contact">Contact no.</label>
      <input type="text" class="form-control" id="contact" placeholder="Contact"  name="contact" required>
    </div>
    </div><br>
    <div class="form-group">
    <label for="inputCity">Gender</label><br>
      <input type="radio" id="male" name="gender" value="male">
      <label for="male">Male</label>
      <input type="radio" id="female" name="gender" value="female">
      <label for="female">Female</label>
      <input type="radio" id="other" name="gender" value="other">
      <label for="other">Other</label>
    </div> 
  <button type="submit" class="btn btn-primary">SignUp</button>
</div>  </div>
</form>
<br>
{% endblock %}